## 1 Setup

### 1.1 Import Libraries

In [1]:
import numpy as np
import pandas as pd

print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)

NumPy version: 2.4.1
Pandas version: 3.0.0

### 1.2 Import Data

#### Mckinsey GDP Dataset

In [2]:
mk_df = pd.read_csv("data/mckinsey.csv")
mk_df.head(3)

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710

#### Employees Dataset

In [3]:
employee_data = {
    "Name": ["Alex", "Ajax", "Jane", "John", "Anna"],
    "Age": [31, 31, 28, 35, 40],
    "Role": ["Senior SD", "Associate Architect", "Junior SD", "Architect", "V.P."],
    "DOJ": ["01-06-2021", "01-01-2025", "01-03-2023", "01-12-2022", "01-08-2000"],
}

emp_df = pd.DataFrame(data=employee_data)
emp_df

   Name  Age                 Role         DOJ
0  Alex   31            Senior SD  01-06-2021
1  Ajax   31  Associate Architect  01-01-2025
2  Jane   28            Junior SD  01-03-2023
3  John   35            Architect  01-12-2022
4  Anna   40                 V.P.  01-08-2000

### 1.3 Update Index

Before accessing rows using indices lets update index of DataFrame to create distinction between row-explicit index and row-implicit index.

#### Mckinskey `DataFrame`

##### Old Explicit Indices

For the `mk_df` DataFrame, old explicit row indices range from 0 to 1703 as seen below.

In [4]:
mk_df.index.values

array([   0,    1,    2, ..., 1701, 1702, 1703], shape=(1704,))

In [5]:
mk_df.index = range(1, len(mk_df) + 1)

##### New Explicit Indices

For the `mk_df` DataFrame, new explicit row indices range from 1 to 1704 as seen below.

In [6]:
mk_df.index.values

array([   1,    2,    3, ..., 1702, 1703, 1704], shape=(1704,))

#### Employee `DataFrame`

Explicit row indices can be strings hence using custom string indices for `emp_df`.

##### Old Explicit Indices

In [7]:
emp_df.index.values

array([0, 1, 2, 3, 4])

In [8]:
emp_df.index = ["E01", "E02", "E03", "E04", "E05"]

##### New Explicit Indices

In [9]:
emp_df.index.values

<StringArray>
['E01', 'E02', 'E03', 'E04', 'E05']
Length: 5, dtype: str

## 2 Implicit vs Explicit Index

### 2.1 The Problem

#### Case #1: Using Single Index

In [10]:
try:
    mk_df[1]
except KeyError as err:
    print("KeyError:", err)

KeyError: 1

In [11]:
try:
    emp_df["E05"]
except KeyError as err:
    print("KeyError:", err)

KeyError: 'E05'

#### Case #2: Using Multiple Index

In [12]:
try:
    mk_df[1, 2, 3]
except KeyError as err:
    print("KeyError:", err)

KeyError: (1, 2, 3)

In [13]:
try:
    emp_df["E03", "E04", "EO5"]
except KeyError as err:
    print("KeyError:", err)

KeyError: ('E03', 'E04', 'EO5')

#### Case #3: Using Slicing

In [14]:
mk_df[100:115:5]

        country  year  population continent  life_exp       gdp_cap
101  Bangladesh  1972    70759295      Asia    45.252    630.233627
106  Bangladesh  1997   123315288      Asia    59.412    972.770035
111     Belgium  1962     9218400    Europe    70.250  10991.206760

In [15]:
emp_df["E03":"EO5"]

     Name  Age       Role         DOJ
E03  Jane   28  Junior SD  01-03-2023
E04  John   35  Architect  01-12-2022
E05  Anna   40       V.P.  01-08-2000

In [16]:
# DataFrame with string index and a column named 'b'
df = pd.DataFrame(
    {
        "a": [10, 20, 30],
        "b": [100, 200, 300],
        "c": [1000, 2000, 3000],
    },
    # Now the index has 'b', and there's also a column 'b'
    index=["a", "b", "c"],
)
df

    a    b     c
a  10  100  1000
b  20  200  2000
c  30  300  3000

In [17]:
df["c"]

a    1000
b    2000
c    3000
Name: c, dtype: int64

In [18]:
df["c":]

    a    b     c
c  30  300  3000

In [19]:
df = pd.DataFrame(
    [
        [10, 100, 1000],
        [20, 200, 2000],
        [30, 300, 3000],
    ],
)
df

    0    1     2
0  10  100  1000
1  20  200  2000
2  30  300  3000

In [20]:
df[2]

0    1000
1    2000
2    3000
Name: 2, dtype: int64

In [21]:
df[2:]

    0    1     2
2  30  300  3000

### 2.2 Solution

1. `loc`
2. `iloc`

## 3 Access Rows

### 3.1 Using `loc`

`mk_df` DataFrame for reference:

In [22]:
mk_df.head(2)

       country  year  population continent  life_exp     gdp_cap
1  Afghanistan  1952     8425333      Asia    28.801  779.445314
2  Afghanistan  1957     9240934      Asia    30.332  820.853030

#### Case #1: Using Single Index

In [23]:
mk_df.loc[1]

country       Afghanistan
year                 1952
population        8425333
continent            Asia
life_exp           28.801
gdp_cap        779.445314
Name: 1, dtype: object

In [24]:
emp_df.loc["E05"]

Name          Anna
Age             40
Role          V.P.
DOJ     01-08-2000
Name: E05, dtype: object

#### Case #2: Using Multiple Index

In [25]:
mk_df.loc[[1, 2, 3]]

       country  year  population continent  life_exp     gdp_cap
1  Afghanistan  1952     8425333      Asia    28.801  779.445314
2  Afghanistan  1957     9240934      Asia    30.332  820.853030
3  Afghanistan  1962    10267083      Asia    31.997  853.100710

In [26]:
emp_df.loc[["E03", "E04", "E05"]]

     Name  Age       Role         DOJ
E03  Jane   28  Junior SD  01-03-2023
E04  John   35  Architect  01-12-2022
E05  Anna   40       V.P.  01-08-2000

#### Case #3: Using Slicing

In [27]:
mk_df.loc[100:115:5]

        country  year  population continent  life_exp       gdp_cap
100  Bangladesh  1967    62821884      Asia    43.453    721.186086
105  Bangladesh  1992   113704579      Asia    56.018    837.810164
110     Belgium  1957     8989111    Europe    69.240   9714.960623
115     Belgium  1982     9856303    Europe    73.930  20979.845890

In [28]:
emp_df.loc["E03":"E05"]

     Name  Age       Role         DOJ
E03  Jane   28  Junior SD  01-03-2023
E04  John   35  Architect  01-12-2022
E05  Anna   40       V.P.  01-08-2000

### 3.2 Using `iloc`

1. Since Implicit index supports negative values `iloc` supports negative value.
2. End index is exclusive while slicing.

`mk_df` DataFrame for reference:

In [29]:
mk_df.head(2)

       country  year  population continent  life_exp     gdp_cap
1  Afghanistan  1952     8425333      Asia    28.801  779.445314
2  Afghanistan  1957     9240934      Asia    30.332  820.853030

#### Case #1: Using Single Index

In [30]:
mk_df.iloc[0]

country       Afghanistan
year                 1952
population        8425333
continent            Asia
life_exp           28.801
gdp_cap        779.445314
Name: 1, dtype: object

In [31]:
emp_df.iloc[4]

Name          Anna
Age             40
Role          V.P.
DOJ     01-08-2000
Name: E05, dtype: object

#### Case #2: Using Multiple Index

In [32]:
mk_df.iloc[[0, 10, 1703]]

          country  year  population continent  life_exp     gdp_cap
1     Afghanistan  1952     8425333      Asia    28.801  779.445314
11    Afghanistan  2002    25268405      Asia    42.129  726.734055
1704     Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [33]:
emp_df.iloc[[4, 1, 3]]

     Name  Age                 Role         DOJ
E05  Anna   40                 V.P.  01-08-2000
E02  Ajax   31  Associate Architect  01-01-2025
E04  John   35            Architect  01-12-2022

#### Case #3: Using Slicing

In [34]:
mk_df.iloc[100:115:5]

        country  year  population continent  life_exp       gdp_cap
101  Bangladesh  1972    70759295      Asia    45.252    630.233627
106  Bangladesh  1997   123315288      Asia    59.412    972.770035
111     Belgium  1962     9218400    Europe    70.250  10991.206760

With `iloc` the end index is exclusive and it works on implicit index.

In [35]:
emp_df.iloc[0:3]

     Name  Age                 Role         DOJ
E01  Alex   31            Senior SD  01-06-2021
E02  Ajax   31  Associate Architect  01-01-2025
E03  Jane   28            Junior SD  01-03-2023

In [36]:
mk_df.iloc[1:10:2]

        country  year  population continent  life_exp     gdp_cap
2   Afghanistan  1957     9240934      Asia    30.332  820.853030
4   Afghanistan  1967    11537966      Asia    34.020  836.197138
6   Afghanistan  1977    14880372      Asia    38.438  786.113360
8   Afghanistan  1987    13867957      Asia    40.822  852.395945
10  Afghanistan  1997    22227415      Asia    41.763  635.341351

In [37]:
mk_df.iloc[-1:-10:-2]

       country  year  population continent  life_exp     gdp_cap
1704  Zimbabwe  2007    12311143    Africa    43.487  469.709298
1702  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1700  Zimbabwe  1987     9216418    Africa    62.351  706.157306
1698  Zimbabwe  1977     6642107    Africa    57.674  685.587682
1696  Zimbabwe  1967     4995432    Africa    53.995  569.795071

### 3.3 Conclusion

## 4 Access Columns

### 4.1 Using Lables

#### Case #1: Using Single Index

`emp_df` DataFrame for reference:

In [38]:
emp_df.head(2)

     Name  Age                 Role         DOJ
E01  Alex   31            Senior SD  01-06-2021
E02  Ajax   31  Associate Architect  01-01-2025

##### Example #1

In [39]:
emp_df["Name"]

E01    Alex
E02    Ajax
E03    Jane
E04    John
E05    Anna
Name: Name, dtype: str

Explicit row index can be used with Series.

In [40]:
emp_df["Name"]["E05"]

'Anna'

##### Example #2

Explicit row index can be used with Series.

In [41]:
mk_df["continent"][1702]

'Africa'

#### Case #2: Using Multiple Index

In [42]:
emp_df[["Name", "Age", "Role"]]

     Name  Age                 Role
E01  Alex   31            Senior SD
E02  Ajax   31  Associate Architect
E03  Jane   28            Junior SD
E04  John   35            Architect
E05  Anna   40                 V.P.

#### Case #3: Using Slicing

Column slicing is not possible directly (i.e., without using `loc` or `iloc`).

### 4.2 Using `loc`

`mk_df` DataFrame for reference:

In [43]:
mk_df.head(2)

       country  year  population continent  life_exp     gdp_cap
1  Afghanistan  1952     8425333      Asia    28.801  779.445314
2  Afghanistan  1957     9240934      Asia    30.332  820.853030

#### Case #1: Using single column name

In [44]:
mk_df.loc[1, "country"]

'Afghanistan'

In [45]:
type(mk_df.loc[1, "country"])

str

In [46]:
mk_df.loc[1, ["country"]]

country    Afghanistan
Name: 1, dtype: str

In [47]:
type(mk_df.loc[1, ["country"]])

pandas.Series

#### Case #2: Using multiple column names

In [48]:
mk_df.loc[1, ["country", "year"]]

country    Afghanistan
year              1952
Name: 1, dtype: object

In [49]:
type(mk_df.loc[1, ["country", "year"]])

pandas.Series

#### Case #3: Using slicing on column names

In [50]:
mk_df.loc[:2, "year":"continent"]

   year  population continent
1  1952     8425333      Asia
2  1957     9240934      Asia

In [51]:
mk_df.loc[0:3, "country":"population"]

       country  year  population
1  Afghanistan  1952     8425333
2  Afghanistan  1957     9240934
3  Afghanistan  1962    10267083

In [52]:
mk_df.loc[6:3:-1, "country"::2]

       country  population  life_exp
6  Afghanistan    14880372    38.438
5  Afghanistan    13079460    36.088
4  Afghanistan    11537966    34.020
3  Afghanistan    10267083    31.997

### 4.2 Using `iloc`

`emp_df` for reference.

In [53]:
emp_df.head(3)

     Name  Age                 Role         DOJ
E01  Alex   31            Senior SD  01-06-2021
E02  Ajax   31  Associate Architect  01-01-2025
E03  Jane   28            Junior SD  01-03-2023

#### Case #1: Using Single Index

In [54]:
emp_df.iloc[0, 0]

'Alex'

#### Case #2: Using Multiple Index

In [55]:
emp_df.iloc[[0, 1, 2], [0, 3]]

     Name         DOJ
E01  Alex  01-06-2021
E02  Ajax  01-01-2025
E03  Jane  01-03-2023

#### Case #3: Using Slicing

In [56]:
emp_df.iloc[:4, :3]

     Name  Age                 Role
E01  Alex   31            Senior SD
E02  Ajax   31  Associate Architect
E03  Jane   28            Junior SD
E04  John   35            Architect

## 5 Access Index

## 6 Insert Rows

In [57]:
emp_df

     Name  Age                 Role         DOJ
E01  Alex   31            Senior SD  01-06-2021
E02  Ajax   31  Associate Architect  01-01-2025
E03  Jane   28            Junior SD  01-03-2023
E04  John   35            Architect  01-12-2022
E05  Anna   40                 V.P.  01-08-2000

### 6.1 Using `loc`

In [58]:
emp_df.loc["E06"] = ["Bob", 30, "Junior SD", "01-07-2024"]
emp_df

     Name  Age                 Role         DOJ
E01  Alex   31            Senior SD  01-06-2021
E02  Ajax   31  Associate Architect  01-01-2025
E03  Jane   28            Junior SD  01-03-2023
E04  John   35            Architect  01-12-2022
E05  Anna   40                 V.P.  01-08-2000
E06   Bob   30            Junior SD  01-07-2024

Hence its is possible to add new row using `loc`.

### 6.2 Using `iloc`

##### Example #1

Fetch explicit indices

In [59]:
# [mk_df.index.get_loc(exp_idx) for exp_idx in mk_df.index]
np.where(mk_df.index.values)

(array([   0,    1,    2, ..., 1701, 1702, 1703], shape=(1704,)),)

In [60]:
try:
    mk_df.iloc[1704] = ["Zimbabwe", 2008, 12311143, "Africa", 43.487, 469.709298]
except IndexError as err:
    print("IndexError:", err)

IndexError: iloc cannot enlarge its target object

##### Example #2

Fetch explicit indices

In [61]:
# [emp_df.index.get_loc(exp_idx) for exp_idx in emp_df.index]
np.where(emp_df.index.values)

(array([0, 1, 2, 3, 4, 5]),)

In [62]:
try:
    emp_df.iloc[6] = ["Kavin", 30, "Junior SD", "01-07-2025"]
except IndexError as err:
    print("IndexError:", err)

IndexError: iloc cannot enlarge its target object

Hence its is **NOT** possible to add new row using `iloc`.