## 1 Setup

### 1.1 Import Libraries

In [1]:
from datetime import datetime

import numpy as np
import pandas as pd

print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)

NumPy version: 2.4.1
Pandas version: 3.0.0

### 1.2 Import Data

#### Mckinsey GDP Dataset

In [2]:
mk_df = pd.read_csv("data/mckinsey.csv")
mk_df.head(3)

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710

#### Employees Dataset

In [3]:
employee_data = [
    ["Ajax", 31, "Senior SD", "01-01-2025"],
    ["Alex", 31, "Senior SD", "01-06-2021"],
    ["Anna", 40, "V.P.", "01-08-2000"],
    ["Jane", 28, "Junior SD", "01-03-2023"],
    ["John", 35, "Architect", "01-12-2022"],
    ["Anna", 40, "V.P.", "01-08-2000"],
]

column_names = ["Name", "Age", "Role", "D.O.J"]

emp_df = pd.DataFrame(data=employee_data, columns=column_names)
emp_df.head()

   Name  Age       Role       D.O.J
0  Ajax   31  Senior SD  01-01-2025
1  Alex   31  Senior SD  01-06-2021
2  Anna   40       V.P.  01-08-2000
3  Jane   28  Junior SD  01-03-2023
4  John   35  Architect  01-12-2022

In [4]:
# emp_df["D.O.J"] = pd.to_datetime(emp_df["D.O.J"], format="%d-%m-%Y")
# emp_df["D.O.J"].info()

## 2 Duplicate Data

### 2.1 Fetch Duplicates

Check for duplicate data in DataFrame.

In [5]:
fltr = emp_df.duplicated()
fltr

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [6]:
type(fltr)

pandas.Series

In [7]:
emp_df[fltr]

   Name  Age  Role       D.O.J
5  Anna   40  V.P.  01-08-2000

In [8]:
emp_df

   Name  Age       Role       D.O.J
0  Ajax   31  Senior SD  01-01-2025
1  Alex   31  Senior SD  01-06-2021
2  Anna   40       V.P.  01-08-2000
3  Jane   28  Junior SD  01-03-2023
4  John   35  Architect  01-12-2022
5  Anna   40       V.P.  01-08-2000

### 2.2 Delete Duplicates

#### Entire DataFrame

In [9]:
emp_df.drop_duplicates()

   Name  Age       Role       D.O.J
0  Ajax   31  Senior SD  01-01-2025
1  Alex   31  Senior SD  01-06-2021
2  Anna   40       V.P.  01-08-2000
3  Jane   28  Junior SD  01-03-2023
4  John   35  Architect  01-12-2022

In [10]:
emp_df.drop_duplicates(inplace=True, keep="last")

#### Subset

In [11]:
emp_df["Role"].value_counts()

Role
Senior SD    2
Junior SD    1
Architect    1
V.P.         1
Name: count, dtype: int64

In [12]:
emp_df.drop_duplicates(subset=["Role"])

   Name  Age       Role       D.O.J
0  Ajax   31  Senior SD  01-01-2025
3  Jane   28  Junior SD  01-03-2023
4  John   35  Architect  01-12-2022
5  Anna   40       V.P.  01-08-2000

In [13]:
emp_df.drop_duplicates(subset=["Role"], keep="last")

   Name  Age       Role       D.O.J
1  Alex   31  Senior SD  01-06-2021
3  Jane   28  Junior SD  01-03-2023
4  John   35  Architect  01-12-2022
5  Anna   40       V.P.  01-08-2000

## 3 Concatenation

### 3.1 Row Concatenation

#### Insert single row

In [14]:
# New employee record.
new_emp = [
    {
        "Name": "Bob",
        "Age": 30,
        "Role": "Junior SD",
        "D.O.J": "01-07-2024",
    }
]

# Create new DataFrame for new employee record.
new_emp_df1 = pd.DataFrame(data=new_emp)
new_emp_df1

  Name  Age       Role       D.O.J
0  Bob   30  Junior SD  01-07-2024

Observe that new DataFrame has explicit index `0`

In [15]:
# Concatenate new DataFrame to main DataFrame.
emp_df = pd.concat([emp_df, new_emp_df1])
emp_df

   Name  Age       Role       D.O.J
0  Ajax   31  Senior SD  01-01-2025
1  Alex   31  Senior SD  01-06-2021
3  Jane   28  Junior SD  01-03-2023
4  John   35  Architect  01-12-2022
5  Anna   40       V.P.  01-08-2000
0   Bob   30  Junior SD  01-07-2024

> **Note**:
>
> If `ignore_index` parameter of `concat` method is not set to `True` then explicit indices from both the DataFrames are retained as it is.

#### Insert multiple rows

In [16]:
new_emps = [
    ["David", 30, "Junior SD", "01-07-2024"],
    ["Karen", 33, "Associate Architect", "01-07-2024"],
]
column_names = ["Name", "Age", "Role", "D.O.J"]

new_emp_df2 = pd.DataFrame(data=new_emps, columns=column_names)
new_emp_df2

    Name  Age                 Role       D.O.J
0  David   30            Junior SD  01-07-2024
1  Karen   33  Associate Architect  01-07-2024

In [17]:
# Concatenate new DataFrame to main DataFrame.
emp_df = pd.concat([emp_df, new_emp_df2], axis=0, ignore_index=True)
emp_df

    Name  Age                 Role       D.O.J
0   Ajax   31            Senior SD  01-01-2025
1   Alex   31            Senior SD  01-06-2021
2   Jane   28            Junior SD  01-03-2023
3   John   35            Architect  01-12-2022
4   Anna   40                 V.P.  01-08-2000
5    Bob   30            Junior SD  01-07-2024
6  David   30            Junior SD  01-07-2024
7  Karen   33  Associate Architect  01-07-2024

Check explicit indices

In [18]:
emp_df.index.values

array([0, 1, 2, 3, 4, 5, 6, 7])

Check implicit indices

In [19]:
np.where(emp_df.index.values)
[emp_df.index.get_loc(exp_idx) for exp_idx in emp_df.index.values]

[0, 1, 2, 3, 4, 5, 6, 7]

> **Note**:
>
> `concat()` method does not have `inplace` parameter.

#### Typecasting

Typecasting "D.O.J" column to `datetime[us]` datatype after concatenating new rows.

##### Before Typecasting

In [20]:
emp_df["D.O.J"].info()

<class 'pandas.Series'>
RangeIndex: 8 entries, 0 to 7
Series name: D.O.J
Non-Null Count  Dtype
--------------  -----
8 non-null      str
dtypes: str(1)
memory usage: 196.0 bytes

In [21]:
emp_df["D.O.J"] = pd.to_datetime(emp_df["D.O.J"], format="%d-%m-%Y")

##### After Typecasting

In [22]:
emp_df["D.O.J"].info()

<class 'pandas.Series'>
RangeIndex: 8 entries, 0 to 7
Series name: D.O.J
Non-Null Count  Dtype
--------------  -----
8 non-null      datetime64[us]
dtypes: datetime64[us](1)
memory usage: 196.0 bytes

In [23]:
emp_df.head(3)

   Name  Age       Role      D.O.J
0  Ajax   31  Senior SD 2025-01-01
1  Alex   31  Senior SD 2021-06-01
2  Jane   28  Junior SD 2023-03-01

### 3.2 Column Concatenation

In [24]:
emp_gender = pd.DataFrame(
    data=["M", "M", "F", "M", "F", "M", "M", "F"],
    columns=["Gender"],
)
emp_gender.head(3)

  Gender
0      M
1      M
2      F

In [25]:
pd.concat([emp_df, emp_gender], axis=1)

    Name  Age                 Role      D.O.J Gender
0   Ajax   31            Senior SD 2025-01-01      M
1   Alex   31            Senior SD 2021-06-01      M
2   Jane   28            Junior SD 2023-03-01      F
3   John   35            Architect 2022-12-01      M
4   Anna   40                 V.P. 2000-08-01      F
5    Bob   30            Junior SD 2024-07-01      M
6  David   30            Junior SD 2024-07-01      M
7  Karen   33  Associate Architect 2024-07-01      F

In [26]:
emp_df.head(2)

   Name  Age       Role      D.O.J
0  Ajax   31  Senior SD 2025-01-01
1  Alex   31  Senior SD 2021-06-01

> **Note**:
>
> 1. `pd.concat` does not have `inplace` parameter it returns a new DataFrame.
> 2. To save the concatenation result it must be reassigned to a DataFrame.

In [27]:
# Concatenate new DataFrame to main DataFrame.
emp_df = pd.concat([emp_df, emp_gender], axis=1)
emp_df.head(3)

   Name  Age       Role      D.O.J Gender
0  Ajax   31  Senior SD 2025-01-01      M
1  Alex   31  Senior SD 2021-06-01      M
2  Jane   28  Junior SD 2023-03-01      F

## 4 Merging

Merging is done using Joins

In [28]:
skill_data = [
    ["Ajax", "Python"],
    ["Alex", "Python"],
    ["Alex", "MySQL"],
    ["Ajax", "MongoDB"],
    ["John", "HLD+LLD"],
    ["Anna", "Business Administration"],
    ["", "JAVA"],
]

skill_df = pd.DataFrame(data=skill_data, columns=["Name", "Skill"])

In [29]:
skill_df.head()

   Name    Skill
0  Ajax   Python
1  Alex   Python
2  Alex    MySQL
3  Ajax  MongoDB
4  John  HLD+LLD

### 4.1 Inner Join

`how` by default is set to `inner`

In [30]:
pd.merge(emp_df, skill_df)

   Name  Age       Role      D.O.J Gender                    Skill
0  Ajax   31  Senior SD 2025-01-01      M                   Python
1  Ajax   31  Senior SD 2025-01-01      M                  MongoDB
2  Alex   31  Senior SD 2021-06-01      M                   Python
3  Alex   31  Senior SD 2021-06-01      M                    MySQL
4  John   35  Architect 2022-12-01      M                  HLD+LLD
5  Anna   40       V.P. 2000-08-01      F  Business Administration

Rename "Name" column in `skill_df` to "EmpName" for clarity.

In [31]:
skill_df.rename({"Name": "EmpName"}, axis=1, inplace=True)

In [32]:
emp_df.merge(skill_df, left_on="Name", right_on="EmpName", how="inner")

   Name  Age       Role      D.O.J Gender EmpName                    Skill
0  Ajax   31  Senior SD 2025-01-01      M    Ajax                   Python
1  Ajax   31  Senior SD 2025-01-01      M    Ajax                  MongoDB
2  Alex   31  Senior SD 2021-06-01      M    Alex                   Python
3  Alex   31  Senior SD 2021-06-01      M    Alex                    MySQL
4  John   35  Architect 2022-12-01      M    John                  HLD+LLD
5  Anna   40       V.P. 2000-08-01      F    Anna  Business Administration

### 4.2 Left Outer Join

In [33]:
emp_df.merge(skill_df, left_on="Name", right_on="EmpName", how="left")

,Name,Age,Role,D.O.J,Gender,EmpName,Skill
0,Ajax,31,Senior SD,2025-01-01,M,Ajax,Python
1,Ajax,31,Senior SD,2025-01-01,M,Ajax,MongoDB
2,Alex,31,Senior SD,2021-06-01,M,Alex,Python
3,Alex,31,Senior SD,2021-06-01,M,Alex,MySQL
4,Jane,28,Junior SD,2023-03-01,F,NaN,NaN
5,John,35,Architect,2022-12-01,M,John,HLD+LLD
6,Anna,40,V.P.,2000-08-01,F,Anna,Business Administration
7,Bob,30,Junior SD,2024-07-01,M,NaN,NaN
8,David,30,Junior SD,2024-07-01,M,NaN,NaN
9,Karen,33,Associate Architect,2024-07-01,F,NaN,NaN

### 4.3 Right Outer Join

In [34]:
emp_df.merge(skill_df, left_on="Name", right_on="EmpName", how="right")

   Name   Age       Role      D.O.J Gender EmpName                    Skill
0  Ajax  31.0  Senior SD 2025-01-01      M    Ajax                   Python
1  Alex  31.0  Senior SD 2021-06-01      M    Alex                   Python
2  Alex  31.0  Senior SD 2021-06-01      M    Alex                    MySQL
3  Ajax  31.0  Senior SD 2025-01-01      M    Ajax                  MongoDB
4  John  35.0  Architect 2022-12-01      M    John                  HLD+LLD
5  Anna  40.0       V.P. 2000-08-01      F    Anna  Business Administration
6   NaN   NaN        NaN        NaT    NaN                             JAVA

### 4.4 Full Outer Join

In [35]:
emp_df.merge(skill_df, left_on="Name", right_on="EmpName", how="outer")

,Name,Age,Role,D.O.J,Gender,EmpName,Skill
0,NaN,NaN,NaN,NaT,NaN,,JAVA
1,Ajax,31.0,Senior SD,2025-01-01,M,Ajax,Python
2,Ajax,31.0,Senior SD,2025-01-01,M,Ajax,MongoDB
3,Alex,31.0,Senior SD,2021-06-01,M,Alex,Python
4,Alex,31.0,Senior SD,2021-06-01,M,Alex,MySQL
5,Anna,40.0,V.P.,2000-08-01,F,Anna,Business Administration
6,Bob,30.0,Junior SD,2024-07-01,M,NaN,NaN
7,David,30.0,Junior SD,2024-07-01,M,NaN,NaN
8,Jane,28.0,Junior SD,2023-03-01,F,NaN,NaN
9,John,35.0,Architect,2022-12-01,M,John,HLD+LLD
10,Karen,33.0,Associate Architect,2024-07-01,F,NaN,NaN

When the column names are same pandas adds suffixes `_x`, `_y` to the column names. For example:

In [36]:
df1 = pd.DataFrame(
    {
        "A": [10, 30],
        "B": [20, 40],
        "C": [30, 60],
    }
)
df2 = pd.DataFrame(
    {
        "A": [10, 30],
        "C": [30, 60],
    }
)
df2.merge(df1, on="A", how="outer")

    A  C_x   B  C_y
0  10   30  20   30
1  30   60  40   60

## 5 Aggregation

### 5.1 Aggregation functions

In [37]:
mk_df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [38]:
mk_df["life_exp"].mean()

np.float64(59.474439366197174)

In [39]:
mk_df["life_exp"].sum()

np.float64(101344.44467999999)

In [40]:
mk_df["life_exp"].count()

np.int64(1704)

In [41]:
mk_df["life_exp"].describe()

count    1704.000000
mean       59.474439
std        12.917107
min        23.599000
25%        48.198000
50%        60.712500
75%        70.845500
max        82.603000
Name: life_exp, dtype: float64

## 6 Sorting

#### Sorting by single column

In [42]:
emp_df.sort_values(by="Age")

    Name  Age                 Role      D.O.J Gender
2   Jane   28            Junior SD 2023-03-01      F
5    Bob   30            Junior SD 2024-07-01      M
6  David   30            Junior SD 2024-07-01      M
0   Ajax   31            Senior SD 2025-01-01      M
1   Alex   31            Senior SD 2021-06-01      M
7  Karen   33  Associate Architect 2024-07-01      F
3   John   35            Architect 2022-12-01      M
4   Anna   40                 V.P. 2000-08-01      F

In [43]:
emp_df.sort_values(by="D.O.J", ascending=False)

    Name  Age                 Role      D.O.J Gender
0   Ajax   31            Senior SD 2025-01-01      M
5    Bob   30            Junior SD 2024-07-01      M
6  David   30            Junior SD 2024-07-01      M
7  Karen   33  Associate Architect 2024-07-01      F
2   Jane   28            Junior SD 2023-03-01      F
3   John   35            Architect 2022-12-01      M
1   Alex   31            Senior SD 2021-06-01      M
4   Anna   40                 V.P. 2000-08-01      F

#### Sorting by multiple columns

In [44]:
emp_df.sort_values(
    by=["Gender", "Age", "D.O.J"],
    ascending=[True, True, False],
)

    Name  Age                 Role      D.O.J Gender
2   Jane   28            Junior SD 2023-03-01      F
7  Karen   33  Associate Architect 2024-07-01      F
4   Anna   40                 V.P. 2000-08-01      F
5    Bob   30            Junior SD 2024-07-01      M
6  David   30            Junior SD 2024-07-01      M
0   Ajax   31            Senior SD 2025-01-01      M
1   Alex   31            Senior SD 2021-06-01      M
3   John   35            Architect 2022-12-01      M

> **Note**:
> 
> Setting the parameter `inplace` to `True` in `sort` function will permanently sort the rows w.r.t selected Series in DataFrame.