## 1 Setup

### 1.1 Import Libraries

In [1]:
import warnings
from datetime import datetime

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore", category=FutureWarning)

print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)

NumPy version: 2.4.1
Pandas version: 3.0.0

### 1.2 Import Dataset

In [2]:
pf_df = pd.read_csv("data/pfizer.csv")

row1, col1 = pf_df.shape
print(f"DataFrame has {row1} rows and {col1} columns.")

pf_df.head()

DataFrame has 18 rows and 15 columns.

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,NaN,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,NaN,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20

### 1.3 Sample Dataset

In [3]:
emp_df = pd.DataFrame(
    {
        "Name": ["Alex", "Ajax", "Jane", "John", "Karen"],
        "Role": ["Senior SD", "Junior SD", "Junior SD", "Architect", "As. Architect"],
        "TotExp": [9, 6, 3, 15, 10],
        "Python": [4, 1, 2, 5, 4],
        "MongoDB": [1, 3, None, 5, 5],
        "MySQL": [3, 2, 2, 6, None],
        "JavaScript": [None, 3, None, 1, 1],
    }
)

row2, col2 = emp_df.shape
print(f"DataFrame has {row2} rows and {col2} columns.")

emp_df

DataFrame has 5 rows and 7 columns.

    Name           Role  TotExp  Python  MongoDB  MySQL  JavaScript
0   Alex      Senior SD       9       4      1.0    3.0         NaN
1   Ajax      Junior SD       6       1      3.0    2.0         3.0
2   Jane      Junior SD       3       2      NaN    2.0         NaN
3   John      Architect      15       5      5.0    6.0         1.0
4  Karen  As. Architect      10       4      5.0    NaN         1.0

In [4]:
emp_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      str
 1   Role        5 non-null      str
 2   TotExp      5 non-null      int64
 3   Python      5 non-null      int64
 4   MongoDB     4 non-null      float64
 5   MySQL       4 non-null      float64
 6   JavaScript  3 non-null      float64
dtypes: float64(3), int64(2), str(2)
memory usage: 412.0 bytes

## 2 Melting

Converting data from wide format to long format.

### 2.1 Example

##### Original DataFrame

In [5]:
emp_df

    Name           Role  TotExp  Python  MongoDB  MySQL  JavaScript
0   Alex      Senior SD       9       4      1.0    3.0         NaN
1   Ajax      Junior SD       6       1      3.0    2.0         3.0
2   Jane      Junior SD       3       2      NaN    2.0         NaN
3   John      Architect      15       5      5.0    6.0         1.0
4  Karen  As. Architect      10       4      5.0    NaN         1.0

##### Melted DataFrame

In [6]:
emp_long_df = emp_df.melt(
    id_vars="Name",
    value_vars=["Python", "MongoDB", "MySQL", "JavaScript"],
    var_name="Tech",
    value_name="Exp",
)

row3, col3 = emp_long_df.shape
print(f"DataFrame has {row3} rows and {col3} columns.")

emp_long_df

DataFrame has 20 rows and 3 columns.

     Name        Tech  Exp
0    Alex      Python  4.0
1    Ajax      Python  1.0
2    Jane      Python  2.0
3    John      Python  5.0
4   Karen      Python  4.0
5    Alex     MongoDB  1.0
6    Ajax     MongoDB  3.0
7    Jane     MongoDB  NaN
8    John     MongoDB  5.0
9   Karen     MongoDB  5.0
10   Alex       MySQL  3.0
11   Ajax       MySQL  2.0
12   Jane       MySQL  2.0
13   John       MySQL  6.0
14  Karen       MySQL  NaN
15   Alex  JavaScript  NaN
16   Ajax  JavaScript  3.0
17   Jane  JavaScript  NaN
18   John  JavaScript  1.0
19  Karen  JavaScript  1.0

## 3 Pivoting

Converting data from long format to wide format.

### 3.1 Example

##### Original DataFrame

In [7]:
emp_df.sort_values(by="Name")

    Name           Role  TotExp  Python  MongoDB  MySQL  JavaScript
1   Ajax      Junior SD       6       1      3.0    2.0         3.0
0   Alex      Senior SD       9       4      1.0    3.0         NaN
2   Jane      Junior SD       3       2      NaN    2.0         NaN
3   John      Architect      15       5      5.0    6.0         1.0
4  Karen  As. Architect      10       4      5.0    NaN         1.0

##### Pivoted DataFrame

If we pivot the melted DataFrame we almost bet back original DataFrame.

In [8]:
emp_wide_df = emp_long_df.pivot(columns="Tech", index="Name", values="Exp")

row4, col4 = emp_wide_df.shape
print(f"DataFrame has {row4} rows and {col4} columns.")

emp_wide_df

DataFrame has 5 rows and 4 columns.

Tech   JavaScript  MongoDB  MySQL  Python
Name
Ajax          3.0      3.0    2.0     1.0
Alex          NaN      1.0    3.0     4.0
Jane          NaN      NaN    2.0     2.0
John          1.0      5.0    6.0     5.0
Karen         1.0      5.0    NaN     4.0

In [9]:
emp_wide_df.reset_index().sort_values(by="Name")

Tech   Name  JavaScript  MongoDB  MySQL  Python
0      Ajax         3.0      3.0    2.0     1.0
1      Alex         NaN      1.0    3.0     4.0
2      Jane         NaN      NaN    2.0     2.0
3      John         1.0      5.0    6.0     5.0
4     Karen         1.0      5.0    NaN     4.0

## 4 Binning

### 4.1 Example

##### Original DataFrame

In [10]:
emp_df

    Name           Role  TotExp  Python  MongoDB  MySQL  JavaScript
0   Alex      Senior SD       9       4      1.0    3.0         NaN
1   Ajax      Junior SD       6       1      3.0    2.0         3.0
2   Jane      Junior SD       3       2      NaN    2.0         NaN
3   John      Architect      15       5      5.0    6.0         1.0
4  Karen  As. Architect      10       4      5.0    NaN         1.0

In [11]:
exp_in_years = [0, 5, 10, 12, np.inf]
roles = [
    "Junior SD",  # (0, 5]
    "Senior SD",  # (5, 10]
    "As. Architect",  # (10, 13]
    "Architect",  # (12, Inf]
]

# Create new column `ElgRole` for eligible role.
emp_df["ElgRole"] = pd.cut(emp_df["TotExp"], bins=exp_in_years, labels=roles)

##### After Binning

In [12]:
emp_df[["Name", "TotExp", "Role", "ElgRole"]].sort_values(by="TotExp")

    Name  TotExp           Role    ElgRole
2   Jane       3      Junior SD  Junior SD
1   Ajax       6      Junior SD  Senior SD
0   Alex       9      Senior SD  Senior SD
4  Karen      10  As. Architect  Senior SD
3   John      15      Architect  Architect

## 5 Handling missing values

### 5.1 `null` representation

Various data types and their null representation.

<div style="display: inline-block">

| Data Type | Null representation |
| --------- | ------------------- |
| String    | None                |
| Float     | NaN                 |
| Boolean   | \<NA\>              |
| DateTime  | NaT                 |

</div>

> **Note**:
>
> Integer datatype does not have any null representation. Integer values are converted to Float and `NaN` represents their null value.

In [13]:
from datetime import datetime as dt

dtypes_df = pd.DataFrame(
    {
        "String": ["A", None, "C", "D", "E"],
        "Integer": [1, 2, 3, None, 5],
        "Float": [None, 2.7, 3.14, 4.0, 5],
        "Boolean": [True, False, None, True, True],
        "DateTime": [dt.now(), dt(2020, 5, 17), None, None, dt(2025, 7, 12)],
        "NoNulls": ["A", 2, 3.14, True, datetime.now()],
    }
)

# dtypes_df["Integer"] = dtypes_df["Integer"].astype("int64")
dtypes_df["Boolean"] = dtypes_df["Boolean"].astype("boolean")

row_count, col_count = dtypes_df.shape

display(dtypes_df)
print(f"Dataframe contains {row_count} rows and {col_count} columns.\n\n")

dtypes_df.info()

,String,Integer,Float,Boolean,DateTime,NoNulls
0,A,1.0,NaN,True,2026-02-09 01:26:33.967574,A
1,NaN,2.0,2.70,False,2020-05-17 00:00:00.000000,2
2,C,3.0,3.14,<NA>,NaT,3.14
3,D,NaN,4.00,True,NaT,True
4,E,5.0,5.00,True,2025-07-12 00:00:00.000000,2026-02-09 01:26:33.967574

Dataframe contains 5 rows and 6 columns.


<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   String    4 non-null      str
 1   Integer   4 non-null      float64
 2   Float     4 non-null      float64
 3   Boolean   4 non-null      boolean
 4   DateTime  3 non-null      datetime64[us]
 5   NoNulls   5 non-null      object
dtypes: boolean(1), datetime64[us](1), float64(2), object(1), str(1)
memory usage: 342.0+ bytes

### 5.2 Fetch Null values

#### `isna()` Method

In [14]:
dtypes_df.isna()

   String  Integer  Float  Boolean  DateTime  NoNulls
0   False    False   True    False     False    False
1    True    False  False    False     False    False
2   False    False  False     True      True    False
3   False     True  False    False      True    False
4   False    False  False    False     False    False

> **Note**:
> 
> `isnull()` is alias for `isna()` both are same.

```python
dtypes_df.isna().any(axis=0)
dtypes_df.isna().all(axis=0)
dtypes_df.isna().any(axis=1)
dtypes_df.isna().all(axis=1)
```

#### Row wise null count

In [15]:
dtypes_df.isna().sum(axis=1)

0    1
1    1
2    2
3    2
4    0
dtype: int64

#### Column wise null count

In [16]:
dtypes_df.isna().sum(axis=0)

String      1
Integer     1
Float       1
Boolean     1
DateTime    2
NoNulls     0
dtype: int64

#### Fetch rows with at least one null

In [17]:
dtypes_df[dtypes_df.isnull().any(axis=1)]

  String  Integer  Float  Boolean                   DateTime NoNulls
0      A      1.0    NaN     True 2026-02-09 01:26:33.967574       A
1    NaN      2.0   2.70    False 2020-05-17 00:00:00.000000       2
2      C      3.0   3.14     <NA>                        NaT    3.14
3      D      NaN   4.00     True                        NaT    True

#### Fetch rows with all null values

In [18]:
dtypes_df2 = dtypes_df.copy()
dtypes_df2.loc[5] = [None, None, None, None, None, None]
dtypes_df2

,String,Integer,Float,Boolean,DateTime,NoNulls
0,A,1.0,NaN,True,2026-02-09 01:26:33.967574,A
1,NaN,2.0,2.7,False,2020-05-17 00:00:00,2
2,C,3.0,3.14,<NA>,NaT,3.14
3,D,NaN,4.0,True,NaT,True
4,E,5.0,5.0,True,2025-07-12 00:00:00,2026-02-09 01:26:33.967574
5,None,None,None,None,None,None

In [19]:
dtypes_df2[dtypes_df2.isna().all(axis=1)]

  String Integer Float Boolean DateTime NoNulls
5   None    None  None    None     None    None

#### Fetch columns with at least one null

In [20]:
dtypes_df.isnull().any(axis=0)

String       True
Integer      True
Float        True
Boolean      True
DateTime     True
NoNulls     False
dtype: bool

#### Fetch columns with all null values

In [21]:
dtypes_df2["AllNulls"] = [None, None, None, None, None, None]
dtypes_df2.isnull().all(axis=0)

String      False
Integer     False
Float       False
Boolean     False
DateTime    False
NoNulls     False
AllNulls     True
dtype: bool

In [22]:
dtypes_df2.isna()

   String  Integer  Float  Boolean  DateTime  NoNulls  AllNulls
0   False    False   True    False     False    False      True
1    True    False  False    False     False    False      True
2   False    False  False     True      True    False      True
3   False     True  False    False      True    False      True
4   False    False  False    False     False    False      True
5    True     True   True     True      True     True      True

### 5.3 Delete Null values

#### `dropna()` Method

In [23]:
dtypes_df.dropna()

  String  Integer  Float  Boolean   DateTime                     NoNulls
4      E      5.0    5.0     True 2025-07-12  2026-02-09 01:26:33.967574

Since all rows contain null values, all rows are deleted from DataFrame.

> **Note**:
>
> `inplace` parameter was not set to `True` to preserve data for further topics.

### 5.4 Handling Null values

1. Delete rows containing null values.
2. Fill missing values with some data (based on some strategy).

#### `fillna()` Method

##### Before filling

In [24]:
dtypes_df

,String,Integer,Float,Boolean,DateTime,NoNulls
0,A,1.0,NaN,True,2026-02-09 01:26:33.967574,A
1,NaN,2.0,2.70,False,2020-05-17 00:00:00.000000,2
2,C,3.0,3.14,<NA>,NaT,3.14
3,D,NaN,4.00,True,NaT,True
4,E,5.0,5.00,True,2025-07-12 00:00:00.000000,2026-02-09 01:26:33.967574

In [25]:
dtypes_df.fillna(
    {
        "String": "",
        "Integer": 0,
        "Float": 0,
        "Boolean": False,
        "DateTime": datetime.now(),
    },
    inplace=True,
)

,String,Integer,Float,Boolean,DateTime,NoNulls
0,A,1.0,0.00,True,2026-02-09 01:26:33.967574,A
1,,2.0,2.70,False,2020-05-17 00:00:00.000000,2
2,C,3.0,3.14,False,2026-02-09 01:26:34.077327,3.14
3,D,0.0,4.00,True,2026-02-09 01:26:34.077327,True
4,E,5.0,5.00,True,2025-07-12 00:00:00.000000,2026-02-09 01:26:33.967574

##### After filling

In [26]:
dtypes_df

,String,Integer,Float,Boolean,DateTime,NoNulls
0,A,1.0,0.00,True,2026-02-09 01:26:33.967574,A
1,,2.0,2.70,False,2020-05-17 00:00:00.000000,2
2,C,3.0,3.14,False,2026-02-09 01:26:34.077327,3.14
3,D,0.0,4.00,True,2026-02-09 01:26:34.077327,True
4,E,5.0,5.00,True,2025-07-12 00:00:00.000000,2026-02-09 01:26:33.967574

> **Note**:
>
> Generally instead of filling missing values with some random values, **Imputation technique** is followed.

#### `interpolate()` method

## 6 String methods

In [27]:
emp_df

    Name           Role  TotExp  Python  MongoDB  MySQL  JavaScript    ElgRole
0   Alex      Senior SD       9       4      1.0    3.0         NaN  Senior SD
1   Ajax      Junior SD       6       1      3.0    2.0         3.0  Senior SD
2   Jane      Junior SD       3       2      NaN    2.0         NaN  Junior SD
3   John      Architect      15       5      5.0    6.0         1.0  Architect
4  Karen  As. Architect      10       4      5.0    NaN         1.0  Senior SD

### 6.1 `contains()` Method

In [28]:
fltr_1 = emp_df["Role"] == "Junior SD"
fltr_1

0    False
1     True
2     True
3    False
4    False
Name: Role, dtype: bool

In [29]:
fltr_2 = emp_df["Role"].str.contains("Junior SD")
fltr_2

0    False
1     True
2     True
3    False
4    False
Name: Role, dtype: bool

In [30]:
display(emp_df[fltr_1])
print("\n")
display(emp_df[fltr_2])

   Name       Role  TotExp  Python  MongoDB  MySQL  JavaScript    ElgRole
1  Ajax  Junior SD       6       1      3.0    2.0         3.0  Senior SD
2  Jane  Junior SD       3       2      NaN    2.0         NaN  Junior SD

   Name       Role  TotExp  Python  MongoDB  MySQL  JavaScript    ElgRole
1  Ajax  Junior SD       6       1      3.0    2.0         3.0  Senior SD
2  Jane  Junior SD       3       2      NaN    2.0         NaN  Junior SD

### 6.2 `split()` Method

In [31]:
emp_df["D.O.J"] = [
    "01-01-2025",
    "01-06-2021",
    "01-08-2000",
    "01-03-2023",
    "01-12-2022",
]

emp_df

,Name,Role,TotExp,Python,MongoDB,MySQL,JavaScript,ElgRole,D.O.J
0,Alex,Senior SD,9,4,1.0,3.0,NaN,Senior SD,01-01-2025
1,Ajax,Junior SD,6,1,3.0,2.0,3.0,Senior SD,01-06-2021
2,Jane,Junior SD,3,2,NaN,2.0,NaN,Junior SD,01-08-2000
3,John,Architect,15,5,5.0,6.0,1.0,Architect,01-03-2023
4,Karen,As. Architect,10,4,5.0,NaN,1.0,Senior SD,01-12-2022

Extract year value from "D.O.J" column

In [32]:
emp_df["D.O.J"].str.split("-").apply(lambda val: val[2])

0    2025
1    2021
2    2000
3    2023
4    2022
Name: D.O.J, dtype: str

In [33]:
emp_df["D.O.J"].str.split("-", expand=True)

    0   1     2
0  01  01  2025
1  01  06  2021
2  01  08  2000
3  01  03  2023
4  01  12  2022

### 6.3 String to Date

#### `to_datetime()` Method

In [34]:
emp_df["D.O.J"].info()

<class 'pandas.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: D.O.J
Non-Null Count  Dtype
--------------  -----
5 non-null      str
dtypes: str(1)
memory usage: 172.0 bytes

In [35]:
emp_df["D.O.J"] = pd.to_datetime(emp_df["D.O.J"], format="%d-%m-%Y")
display(emp_df["D.O.J"].info())
display(emp_df)

<class 'pandas.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: D.O.J
Non-Null Count  Dtype
--------------  -----
5 non-null      datetime64[us]
dtypes: datetime64[us](1)
memory usage: 172.0 bytes

None

,Name,Role,TotExp,Python,MongoDB,MySQL,JavaScript,ElgRole,D.O.J
0,Alex,Senior SD,9,4,1.0,3.0,NaN,Senior SD,2025-01-01
1,Ajax,Junior SD,6,1,3.0,2.0,3.0,Senior SD,2021-06-01
2,Jane,Junior SD,3,2,NaN,2.0,NaN,Junior SD,2000-08-01
3,John,Architect,15,5,5.0,6.0,1.0,Architect,2023-03-01
4,Karen,As. Architect,10,4,5.0,NaN,1.0,Senior SD,2022-12-01

In [36]:
dt_val = emp_df.loc[1, "D.O.J"]
dt_val.day, dt_val.month, dt_val.year

(1, 6, 2021)

#### Convert date to String

In [37]:
dt_val = emp_df.loc[1, "D.O.J"]
dtr_str = dt_val.strftime("%d-%m-%Y")

print("Datatype:", type(dtr_str), "Value:", dtr_str)

Datatype: <class 'str'> Value: 01-06-2021

In [38]:
pd.to_datetime(["20-01-2022"], format="%d-%m-%Y")

DatetimeIndex(['2022-01-20'], dtype='datetime64[us]', freq=None)